config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
    path("users/", include("users.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from .views import dashboard, InfoListView, InfoCreateView, home, generate_pdf, InfoUpdateView, InfoDetailView, InfoDeleteView, HobbiCreateView, SkillCreateView, SkillListView, LanguageCreateView, FormationCreateView, ExperienceCreateView, ExperienceListView, ExperienceDeleteView, SkillDeleteView, FormationListView, FormationDeleteView, LanguageListView, LanguageDeleteView, HobbiListView, HobbyDeleteView
app_name = "pages"

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('home/', home, name='home'),
    path('liste_cv/', InfoListView.as_view(), name='liste_cv'),
    path('create_cv/', InfoCreateView.as_view(), name='create_cv'),
    path('delete_cv/<int:pk>/', InfoDeleteView.as_view(), name='delete_cv'),  
    path('update_cv/<int:pk>/', InfoUpdateView.as_view(), name='update_cv'),
    path('detail_cv/<int:pk>/', InfoDetailView.as_view(), name='detail_cv'),
    
    path('hobbie_create/', HobbiCreateView.as_view(), name='hobbie_create'),
    path('hobbie_list/', HobbiListView.as_view(), name='hobbie_list'),
    path('hobbie_delete/<int:pk>/', HobbyDeleteView.as_view(), name='hobbie_delete'),
    #path('hobbie_update/<int:pk>/', HobbyUpdateView.as_view(), name='hobbie_update'),
    
    path('skill_create/', SkillCreateView.as_view(), name='skill_create'),
    path('skill_list/', SkillListView.as_view(), name='skill_list'),
    path('skill_delete/<int:pk>/', SkillDeleteView.as_view(), name='skill_delete'),
    #path('skill_update/<int:pk>/', SkillUpdateView.as_view(), name='skill_update'),
    
    path('language_create/', LanguageCreateView.as_view(), name='language_create'),
    path('language_list/', LanguageListView.as_view(), name='language_list'),
    path('language_delete/<int:pk>/', LanguageDeleteView.as_view(), name='language_delete'),
    #path('language_update/<int:pk>/', LanguageUpdateView.as_view(), name='language_update'),
    
    path('formation_create/', FormationCreateView.as_view(), name='formation_create'),
    path('formation_list/', FormationListView.as_view(), name='formation_list'),
    path('formation_delete/<int:pk>/', FormationDeleteView.as_view(), name='formation_delete'),
    #path('formation_update/<int:pk>/', FormationUpdateView.as_view(), name='formation_update'),
    
    path('experience_create/', ExperienceCreateView.as_view(), name='experience_create'),
    path('experience_list/', ExperienceListView.as_view(), name='experience_list'),
    path('experience_delete/<int:pk>/', ExperienceDeleteView.as_view(), name='experience_delete'),
    

    path('curriculum-pdf-/<int:pk>/', generate_pdf, name='detail_cv_pdf'),
    

]

templates/pages/dashboard.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% load crispy_forms_tags %}


{% block content %}

<header class="container mx-auto m-6 flex flex-col justify-center items-center">
    <h1 class="font-bold text-4xl mt-4">Bienvenue sur GEN.CV</h1>
    {% if user.is_authenticated %}
        <h2 class="font-bold text-2xl mt-2">{{ user.username }} est authentifié</h2>
    {% endif %}
</header>

<main class="container mx-auto p-10 ">
    <section class="w-full flex flex-row justify-between gap-4">

    </section>
</main>

{% endblock content %}

templates/pages/detail_cv copy.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% load crispy_forms_tags %}


{% block content %}

  <div class='w-full flex justify-end mb-[50px] '>
    <a 
      class="btn btn-primary my-2 w-22 flex justify-end mr-1 "
      href="#" onclick="window.history.back(); return false;">
      Retour
    </a>
  </div>

  <div class=' p-6 flex flex-row justify-center items-center gap-4'>

    <div class='w-auto h-auto flex flex-col justify-center items-center gap-4'>
      <div class='w-44  border-2 rounded-md  '>
        <img 
        class='w-44 h-44 rounded-md object-cover'
        src="{{ info.photo.url }}" alt="Photo de {{ info.firstname }} {{ info.lastname }}">
      </div>

      <div class='flex flex-row justify-center items-center w-full h-auto '>
        <a href="{% url 'pages:detail_cv_pdf_style_1' pk=info.pk %}" class="btn btn-primary w-44">Download style 1 </a>
      </div>
    </div>

    <div class='w-auto h-auto flex flex-col justify-center items-center gap-4'>
      <div class='w-44  border-2 rounded-md  '>
        <img 
        class='w-44 h-44 rounded-md object-cover'
        src="{{ info.photo.url }}" alt="Photo de {{ info.firstname }} {{ info.lastname }}">
      </div>

      <div class='flex flex-row justify-center items-center w-full h-auto '>
        <a href="{% url 'pages:detail_cv_pdf_style_2' pk=info.pk %}" class="btn btn-primary w-44">Download style 2</a>
      </div>
    </div>


    <div class='w-auto h-auto flex flex-col justify-center items-center gap-4'>
      <div class='w-44  border-2 rounded-md  '>
        <img 
        class='w-44 h-44 rounded-md object-cover'
        src="{{ info.photo.url }}" alt="Photo de {{ info.firstname }} {{ info.lastname }}">
      </div>

      <div class='flex flex-row justify-center items-center w-full h-auto '>
        <a href="{% url 'pages:detail_cv_pdf_style_3' pk=info.pk %}" class="btn btn-primary w-44">Download style 3</a>
      </div>
    </div>

  </div>

  <main class="container mx-auto ">
    <section class="flex flex-col w-full">
      <div class="container mx-auto flex flex-col bg-white">

        <div class='flex flex-row justify-start items-start w-full p-4 gap-11'>
          <div class='flex flex-col w-1/4  h-full'>
              <h3 class="flex justify-center font-bold text-4xl mt-2">{{ info.lastname }}</h3>
              <h4 class="flex justify-center font-bold text-4xl mt-2">{{ info.firstname }}</h4>


              <h4 class="text-xl my-10 ">{{ info.type_of_Contract }}</h4>




              <div class="flex justify-center items-center w-full my-2">
                <img 
                class='w-52 h-52 rounded-full border-2 border-gray-400 object-cover'
                src="{{ info.photo.url }}" alt="Photo de {{ info.firstname }} {{ info.lastname }}">
              </div>
              <p class="text-2xl font-bold  mt-10 mb-4">Informations personnelles</p>
              <p class='info-field  text-xl  mt-4'><strong>Adresse:</strong></p>
              <p class="text-lg mt-2">{{ info.address }}</p>
              <p class="text-lg mt-2">{{ info.zip_code }} - {{ info.city }}</p>
              <p class="text-lg mt-2">{{ info.state }}</p>
              <p class="text-lg mt-2"><strong>Téléphone:</strong> {{ info.phone }}</p>
              <p class="text-lg mt-2"><strong>Email:</strong> {{ info.email }}</p>
              
              <div class="info-field mt-2 text-md"><strong>Née le: </strong>{{ info.date_of_birth }} </div>
              <div class="info-field mt-2 text-md"><strong>Lieux : </strong> {{ info.place_of_birth }} </div>

              <div class="info-field  text-xl mt-12  my-4">
                <strong>Hobbies:</strong>
                <div class='px-2 text-lg '>
                  {% for hobby in info.hobbies.all %}
                    - {{ hobby.title_hobby }}{% if not forloop.last %},<br/> {% endif %}
                  {% endfor %}
                </div>
              </div>

              <div class="info-field  text-xl  my-4">
                <strong>Langues:</strong>
                <div class='px-2 text-lg '>
                  {% for language in info.languages.all %}
                      - {{ language.title_language }} : {{ language.niveau_language }}
                    {% if not forloop.last %}, <br/> {% endif %}
                  {% endfor %}
                </div>
              </div>

              <div class="info-field  text-xl  my-4">
                <strong>Compétences:</strong>
                <div class='px-2 text-lg '>
                  {% for skill in info.skills.all %}
                    - {{ skill.title_Skill }}
                    {% if not forloop.last %},<br/>{% endif %}
                  {% endfor %}
                </div>
              </div>
            </div>





            <div class="flex flex-col justify-start items-center w-3/4 h-full">
              <div class=" border-2 border-slate-400 rounded-md  p-2 flex flex-col justify-start items-start w-full ">
                  <p class='px-4 my-4 text-lg'>{{ info.motivation }}</p>
              </div>

              
              <div class="flex flex-col justify-evenly items-center h-full">

              <div class="my-6   w-full">
                <h3 class="w-full flex flex-row justify-center items-center text-3xl mb-6 font-bold ">Experience</h3>
                <div class='px-4'>
                  {% for experience in info.experiences.all %}
                    <p class='flex justify-start w-full text-xl border-b-4 mb-4'> {{ experience.title_experience }}: </p>

                    <div class='flex flex-row justify-start items-start w-full '>
                    
                      <div class='text-lg w-auto flex flex-col justify-start items-start'>
                          <p class='text-sm w-auto mr-6'> {{ experience.start_date_of_experience|date:"d/m/Y" }}</p>
                          <p class='text-sm w-auto mr-6'> {{ experience.end_date_of_experience|date:"d/m/Y" }}</p>
                      </div>

                      <div class='text-lg w-auto flex flex-col justify-start items-start'>
                          <p class='font-bold'>{{ experience.description_experience }}</p>
                          <p>Entreprise: {{ experience.business }} à {{ experience.location_experience }}</p>
                      </div>

                    </div>
                    
                    {% if not forloop.last %}<br/>{% endif %}
                  {% endfor %}
                </div>
              </div> 
              

              <div class=" my-6   w-full">
                <h3 class="w-full flex flex-row justify-center items-center text-3xl mb-6  font-bold ">Formation</h3>
                <div class='px-4'>
                  {% for formation in info.formations.all %}
                  <p class='flex justify-start w-full text-xl border-b-4 mb-4'> {{ formation.title_formation }}: </p>
                  <div class='flex flex-row justify-start items-start w-full '>

                    <div class='text-lg w-auto flex flex-col justify-start items-start'>
                        <h class='text-sm w-auto mr-6'> {{ formation.start_date_of_formation|date:"d/m/Y" }}</h>
                        <h class='text-sm w-auto mr-6'> {{ formation.end_date_of_formation|date:"d/m/Y" }}</h>
                    </div>
                  
                    <div class='text-lg w-auto flex flex-col justify-start items-start'>
                        <p>{{ formation.description_formation }}</p>
                        <p>Entreprise: {{ formation.business }} à {{ formation.location_formation }}</p>

                    </div>
                  
                  </div>
                    {% if not forloop.last %}<br/>{% endif %}
                  {% endfor %}
                </div>
              </div> 
            </div>  
          
          </div>  
        </div>
        
      </div>
    </section>

</main>



{% endblock %}

templates/pages/experience_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% load crispy_forms_tags %}


{% block content %}

<header class="container mx-auto m-6 flex flex-col justify-center items-center">
    <h1 class="font-bold text-4xl mt-4">Bienvenue sur GEN.CV</h1>
    {% if user.is_authenticated %}
        <h2 class="font-bold text-2xl mt-2">{{ user.username }} est authentifié</h2>
    {% endif %}
</header>


<div class="container mx-auto m-6 flex flex-col justify-center items-center">
    <h2 class='text-2xl w-full flex justify-center items-center mt-10'>Êtes-vous sûr de vouloir supprimer cette expérience ?</h2>
    <form method="post">
      {% csrf_token %}
      <button 
      class='text-2xl mt-10
      bg-red-500 hover:bg-red-700 transition duration-400
      text-white font-bold py-2 px-12 rounded-full'
      type="submit" value="Supprimer">
        Supprimer
      </button>
  </form>
  <a href="{% url 'pages:liste_cv' %}" 
    class='text-2xl mt-10 border-2 py-2 px-8 rounded-lg hover:bg-slate-100 hover:text-black transition duration-400'>
    Retour à la liste des CV
  </a>
</div>  
{% endblock %}

templates/pages/experience_list.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% load crispy_forms_tags %}


{% block content %}
<div class='w-full flex justify-end mt-[500px] fixed '>
  <a 
    class="btn btn-primary my-2 w-22 flex justify-end"
    href="#" onclick="window.history.back(); return false;">
    Retour
  </a>
</div>

<header class="container mx-auto m-6 flex flex-col justify-center items-center">
    <h1 class="font-bold text-4xl mt-4">Bienvenue sur GEN.CV</h1>
    {% if user.is_authenticated %}
        <h2 class="font-bold text-2xl mt-2">{{ user.username }} est authentifié</h2>
    {% endif %}
</header>

<main class="container mx-auto p-10">
  <section class="flex flex-col w-full h-full">
      <h1 class='text-4xl font-semibold flex flex-row justify-center items-center py-4'>Liste des expériences</h1>
      <div class="container mx-auto flex flex-col">
        {% for experience in experiences %}
        <div class='flex flex-row justify-center items-center w-full h-auto px-6 my-10 border-2 rounded-md p-2'>
          <div class='flex flex-col justify-center items-center w-full '>
          <p class='w-full text-2xl font-semibold'>{{ experience.title_experience }}</p>
          <p class='w-full text-xl'><strong>Description: </strong>{{experience.description_experience}}</p>
          <p class='w-full text-xl'><strong>Date: </strong>{{experience.date_experience}}</p>
          <p class='w-full text-xl'><strong>Lieu: </strong>{{experience.location_experience}}</p>
        </div>
          <a href="{% url 'pages:experience_delete' experience.pk %}" class="btn btn-primary w-44 mr-6">Supprimer une expérience</a>
          
        </div>
        {% endfor %}
      </div>
    </section>

</main>


{% endblock %}

templates/pages/formation_list.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% load crispy_forms_tags %}


{% block content %}
<div class='w-full flex justify-end mt-[500px] fixed '>
  <a 
    class="btn btn-primary my-2 w-22 flex justify-end"
    href="#" onclick="window.history.back(); return false;">
    Retour
  </a>
</div>

<header class="container mx-auto m-6 flex flex-col justify-center items-center">
    <h1 class="font-bold text-4xl mt-4">Bienvenue sur GEN.CV</h1>
    {% if user.is_authenticated %}
        <h2 class="font-bold text-2xl mt-2">{{ user.username }} est authentifié</h2>
    {% endif %}
</header>

<main class="container mx-auto p-10">
  <section class="flex flex-col w-full h-full">
      <h1 class='text-4xl font-semibold flex flex-row justify-center items-center py-4'>Liste des formations</h1>
      <div class="container mx-auto flex flex-col">
        {% for formation in formations %}
        <div class='flex flex-row justify-center items-center w-full h-auto px-6 my-10 border-2 rounded-md p-2'>
          <div class='flex flex-col justify-center items-center w-full '>
          <p class='w-full text-2xl font-semibold'>{{ formation.title_formation }}</p>
          <p class='w-full text-xl'><strong>Description: </strong>{{formation.description_formation}}</p>
          <p class='w-full text-xl'><strong>Date: </strong>{{formation.date_formation}}</p>
          <p class='w-full text-xl'><strong>Lieu: </strong>{{formation.location_formation}}</p>
        </div>
          <a href="{% url 'pages:formation_delete' formation.pk %}" class="btn btn-primary w-44 mr-6">Supprimer une formation</a>
          
        </div>
        {% endfor %}
      </div>
    </section>

</main>


{% endblock %}

templates/pages/hobbie_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% load crispy_forms_tags %}


{% block content %}

<header class="container mx-auto m-6 flex flex-col justify-center items-center">
    <h1 class="font-bold text-4xl mt-4">Bienvenue sur GEN.CV</h1>
    {% if user.is_authenticated %}
        <h2 class="font-bold text-2xl mt-2">{{ user.username }} est authentifié</h2>
    {% endif %}
</header>


<div class="container mx-auto m-6 flex flex-col justify-center items-center">
    <h2 class='text-2xl w-full flex justify-center items-center mt-10'>Êtes-vous sûr de vouloir supprimer ce hobbie ?</h2>
    <form method="post">
      {% csrf_token %}
      <button 
      class='text-2xl mt-10
      bg-red-500 hover:bg-red-700 transition duration-400
      text-white font-bold py-2 px-12 rounded-full'
      type="submit" value="Supprimer">
        Supprimer
      </button>
  </form>
  <a href="{% url 'pages:liste_cv' %}" 
    class='text-2xl mt-10 border-2 py-2 px-8 rounded-lg hover:bg-slate-100 hover:text-black transition duration-400'>
    Retour à la liste des CV
  </a>
</div>  
{% endblock %}

templates/pages/language_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% load crispy_forms_tags %}


{% block content %}

<header class="container mx-auto m-6 flex flex-col justify-center items-center">
    <h1 class="font-bold text-4xl mt-4">Bienvenue sur GEN.CV</h1>
    {% if user.is_authenticated %}
        <h2 class="font-bold text-2xl mt-2">{{ user.username }} est authentifié</h2>
    {% endif %}
</header>


<div class="container mx-auto m-6 flex flex-col justify-center items-center">
    <h2 class='text-2xl w-full flex justify-center items-center mt-10'>Êtes-vous sûr de vouloir supprimer cette langue ?</h2>
    <form method="post">
      {% csrf_token %}
      <button 
      class='text-2xl mt-10
      bg-red-500 hover:bg-red-700 transition duration-400
      text-white font-bold py-2 px-12 rounded-full'
      type="submit" value="Supprimer">
        Supprimer
      </button>
  </form>
  <a href="{% url 'pages:liste_cv' %}" 
    class='text-2xl mt-10 border-2 py-2 px-8 rounded-lg hover:bg-slate-100 hover:text-black transition duration-400'>
    Retour à la liste des CV
  </a>
</div>  
{% endblock %}

templates/pages/list.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% load crispy_forms_tags %}


{% block content %}


<header class="container mx-auto m-6 flex flex-col justify-center items-center">

<div class='w-full flex justify-end '>
  <a 
    class="btn btn-primary my-2 w-22 flex justify-end mr-1 "
    href="#" onclick="window.history.back(); return false;">
    Retour
  </a>
</div>

</header>

<main class="container mx-auto p-10">
  <section class="w-full flex flex-row justify-between gap-4">
        <div class="bg-gray-100 p-4 rounded-lg flex flex-col">
            <h2 class="font-bold text-2xl">Créer un CV</h2>
            <p class="mt-2">Créez votre CV en quelques clics</p>
            <a href="{% url 'pages:create_cv' %}" class="btn btn-primary mt-4 w-36">Créer un CV</a>
        </div>
    </section>

    <section class="flex flex-col w-full h-full">
      <h1 class='text-4xl font-semibold flex flex-row justify-center items-center py-4 border-2 rounded-md mt-6'>Liste des curriculums</h1>
      <div class="container mx-auto flex flex-col">
        {% for info in infos %}
        <div class='flex flex-col justify-center items-center w-full h-auto py-6 mx-10'>
          <div class='mb-6'>
            <a href="{% url 'pages:detail_cv' info.pk %}" class='w-full text-4xl font-semibold'>{{ info.title }}</a>
          </div>  
          <div>
            <a href="{% url 'pages:detail_cv' info.pk %}" class="btn btn-primary w-44 mr-6">Détail du CV</a>
            <a href="{% url 'pages:update_cv' info.pk %}" class="btn btn-primary w-44 mr-6">Modifier le CV</a>
            <a href="{% url 'pages:delete_cv' info.pk %}" class="btn btn-primary w-44">Supprimer le CV</a>
        </div>
        </div>
          <div class='flex flex-row justify-start items-start w-full bg-white border-2 p-4 gap-11'>

            
            <div class='flex flex-col w-1/4  h-full'>
              <div class="info-field mt-2 text-4xl">{{ info.lastname }}</div>
              <div class="info-field mt-2 text-4xl"> {{ info.firstname }}</div>

              <p class="text-xl my-10 ">{{ info.type_of_Contract }}</p>

              <div class="flex justify-center items-center w-full mb-6">
                <img 
                class='w-52 h-52 rounded-full border-2 border-gray-400 object-cover'
                src="{{ info.photo.url }}" alt="Photo de {{ info.firstname }} {{ info.lastname }}">
              </div>

              <div class="info-field mt-2 text-md"><strong>Adresse:</strong> {{ info.address }}</div>
              <div class="info-field mt-2 text-md"><strong>Ville:</strong> {{ info.city }}</div>
              <div class="info-field mt-2 text-md"><strong>code postal:</strong> {{ info.zip_code }}</div>
              <div class="info-field mt-2 text-md"><strong>Etat:</strong> {{ info.state }}</div>
              <div class="info-field mt-2 text-md"><strong>Téléphone:</strong> {{ info.phone }}</div>
              <div class="info-field mt-2 text-md"><strong>Email:</strong> {{ info.email }}</div>
              <div class="info-field mt-2 text-md"><strong>Née le: </strong>{{ info.date_of_birth }} </div>
              <div class="info-field mt-2 text-md"><strong>Lieux : </strong> {{ info.place_of_birth }} </div>

              <div class="info-field mt-6  py-2">
                <strong>Hobbies:</strong>
                <div class='px-2'>
                  {% for hobby in info.hobbies.all %}
                    - {{ hobby.title_hobby }}{% if not forloop.last %},<br/> {% endif %}
                  {% endfor %}
                </div>
              </div>

              <div class="info-field mt-2  py-2">
                <strong>Langues:</strong>
                <div class='px-2'>
                  {% for language in info.languages.all %}
                      - {{ language.title_language }} : {{ language.niveau_language }}
                    {% if not forloop.last %}, <br/> {% endif %}
                  {% endfor %}
                </div>
              </div>

              <div class="info-field mt-2  py-2">
                <strong>Compétences:</strong>
                <div class='px-2'>
                  {% for skill in info.skills.all %}
                    - {{ skill.title_Skill }}
                    {% if not forloop.last %},<br/>{% endif %}
                  {% endfor %}
                </div>
              </div>
            </div>

            <div class="flex flex-col justify-start items-center w-3/4 h-full">
              <div class=" border-2 rounded-md my-6 p-2 flex flex-col w-full md:min-h-36">
              
                  <p class='px-4 my-6'>{{ info.motivation }}</p>
              </div>

              <div class="info-field my-6  p-2 w-full">
                <h3 class="w-full flex flex-row justify-center items-center text-4xl mb-6">Experience</h3>
                <div class='px-4'>
                  {% for experience in info.experiences.all %}
                    <p class='text-xl underline mb-4'> {{ experience.title_experience }}: </p>

                    <div class='flex flex-row justify-start items-start w-full '>
                    
                      <div class='text-lg w-auto flex flex-col justify-start items-start'>
                          <h class='text-sm w-auto mr-6'> {{ experience.start_date_of_experience|date:"d/m/Y" }}</h>
                          <h class='text-sm w-auto mr-6'> {{ experience.end_date_of_experience|date:"d/m/Y" }}</h>
                      </div>

                      <div class='text-lg w-auto flex flex-col justify-start items-start'>
                          <p class='font-bold'>{{ experience.description_experience }}</p>
                          <p>Entreprise: {{ experience.business }}</p>
                          <p>Lieu: {{ experience.location_experience }}</p>
                      </div>

                    </div>
                    
                    {% if not forloop.last %}<br/>{% endif %}
                  {% endfor %}
                </div>
              </div> 
            

              <div class="info-field my-6  p-2 w-full">
                <h3 class="w-full flex flex-row justify-center items-center text-4xl mb-6">Formation</h3>
                <div class='px-4'>
                  {% for formation in info.formations.all %}
                  <p class='text-xl underline mb-4'> {{ formation.title_formation }}: </p>
                  <div class='flex flex-row justify-start items-start w-full '>

                    <div class='text-lg w-auto flex flex-col justify-start items-start'>
                        <h class='text-sm w-auto mr-6'> {{ formation.start_date_of_formation|date:"d/m/Y" }}</h>
                        <h class='text-sm w-auto mr-6'> {{ formation.end_date_of_formation|date:"d/m/Y" }}</h>
                    </div>
                  
                    <div class='text-lg w-auto flex flex-col justify-start items-start'>
                        <p>{{ formation.description_formation }}</p>
                        <p>Entreprise: {{ formation.business }}</p>
                        <p>Lieu: {{ formation.location_formation }}</p>
                    </div>
                  
                  </div>
                    {% if not forloop.last %}<br/>{% endif %}
                  {% endfor %}
                </div>
              </div> 
            </div>  
          </div>
        {% endfor %}
      </div>
    </section>

</main>


{% endblock %}

templates/pages/skill_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% load crispy_forms_tags %}


{% block content %}

<header class="container mx-auto m-6 flex flex-col justify-center items-center">
    <h1 class="font-bold text-4xl mt-4">Bienvenue sur GEN.CV</h1>
    {% if user.is_authenticated %}
        <h2 class="font-bold text-2xl mt-2">{{ user.username }} est authentifié</h2>
    {% endif %}
</header>


<div class="container mx-auto m-6 flex flex-col justify-center items-center">
    <h2 class='text-2xl w-full flex justify-center items-center mt-10'>Êtes-vous sûr de vouloir supprimer cette compétence ?</h2>
    <form method="post">
      {% csrf_token %}
      <button 
      class='text-2xl mt-10
      bg-red-500 hover:bg-red-700 transition duration-400
      text-white font-bold py-2 px-12 rounded-full'
      type="submit" value="Supprimer">
        Supprimer
      </button>
  </form>
  <a href="{% url 'pages:liste_cv' %}" 
    class='text-2xl mt-10 border-2 py-2 px-8 rounded-lg hover:bg-slate-100 hover:text-black transition duration-400'>
    Retour à la liste des CV
  </a>
</div>  
{% endblock %}

templates/pages/skill_list.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% load crispy_forms_tags %}


{% block content %}

<div class='w-full flex justify-end mt-[500px] fixed '>
  <a 
    class="btn btn-primary my-2 w-22 flex justify-end"
    href="#" onclick="window.history.back(); return false;">
    Retour
  </a>
</div>

<header class="container mx-auto m-6 flex flex-col justify-center items-center">
    <h1 class="font-bold text-4xl mt-4">Bienvenue sur GEN.CV</h1>
    {% if user.is_authenticated %}
        <h2 class="font-bold text-2xl mt-2">{{ user.username }} est authentifié</h2>
    {% endif %}
</header>

<main class="container mx-auto p-10">


  <section class="flex flex-col w-full h-full">
    <h1 class='text-4xl font-semibold flex flex-row justify-center items-center py-4'>Liste des compétences</h1>
    <div class="container mx-auto flex flex-col">
      {% for skill in skills %}
        <div class='flex flex-row justify-center items-center w-full h-auto px-6 my-10 border-2 rounded-md p-2'>
          <p class='w-full text-2xl font-semibold'>{{ skill.title_Skill }}</p>
          <a href="{% url 'pages:skill_delete' skill.pk %}" class="btn btn-primary w-44 mr-6">Supprimer une compétence</a>
        </div>
      {% endfor %}
    </div>
  </section>

  </main>



{% endblock %}