config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
    path("users/", include("users.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from .views import dashboard, InfoListView, InfoCreateView, home, generate_pdf, InfoUpdateView, InfoDetailView, InfoDeleteView, HobbiCreateView, SkillCreateView, SkillListView, LanguageCreateView, FormationCreateView, ExperienceCreateView, ExperienceListView, ExperienceDeleteView, SkillDeleteView, FormationListView, FormationDeleteView, LanguageListView, LanguageDeleteView, HobbiListView, HobbyDeleteView
app_name = "pages"

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('home/', home, name='home'),
    path('liste_cv/', InfoListView.as_view(), name='liste_cv'),
    path('create_cv/', InfoCreateView.as_view(), name='create_cv'),
    path('delete_cv/<int:pk>/', InfoDeleteView.as_view(), name='delete_cv'),  
    path('update_cv/<int:pk>/', InfoUpdateView.as_view(), name='update_cv'),
    path('detail_cv/<int:pk>/', InfoDetailView.as_view(), name='detail_cv'),
    
    path('hobbie_create/', HobbiCreateView.as_view(), name='hobbie_create'),
    path('hobbie_list/', HobbiListView.as_view(), name='hobbie_list'),
    path('hobbie_delete/<int:pk>/', HobbyDeleteView.as_view(), name='hobbie_delete'),
    #path('hobbie_update/<int:pk>/', HobbyUpdateView.as_view(), name='hobbie_update'),
    
    path('skill_create/', SkillCreateView.as_view(), name='skill_create'),
    path('skill_list/', SkillListView.as_view(), name='skill_list'),
    path('skill_delete/<int:pk>/', SkillDeleteView.as_view(), name='skill_delete'),
    #path('skill_update/<int:pk>/', SkillUpdateView.as_view(), name='skill_update'),
    
    path('language_create/', LanguageCreateView.as_view(), name='language_create'),
    path('language_list/', LanguageListView.as_view(), name='language_list'),
    path('language_delete/<int:pk>/', LanguageDeleteView.as_view(), name='language_delete'),
    #path('language_update/<int:pk>/', LanguageUpdateView.as_view(), name='language_update'),
    
    path('formation_create/', FormationCreateView.as_view(), name='formation_create'),
    path('formation_list/', FormationListView.as_view(), name='formation_list'),
    path('formation_delete/<int:pk>/', FormationDeleteView.as_view(), name='formation_delete'),
    #path('formation_update/<int:pk>/', FormationUpdateView.as_view(), name='formation_update'),
    
    path('experience_create/', ExperienceCreateView.as_view(), name='experience_create'),
    path('experience_list/', ExperienceListView.as_view(), name='experience_list'),
    path('experience_delete/<int:pk>/', ExperienceDeleteView.as_view(), name='experience_delete'),
    

    path('curriculum-pdf-/<int:pk>/', generate_pdf, name='detail_cv_pdf'),
    

]

users/urls.py
from django.urls import path, include

from . import views


app_name = "users"

urlpatterns = [
    path('logout/', views.custom_logout_view, name='logout'),
    path("signup/", views.signup, name="signup"),
    path('login/', views.login_view, name='login'),
    path('user-info/', views.user_info_view, name='user_info'),
]

templates/base.html
{% load static django_vite %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% vite_hmr_client %}
    {% vite_asset 'src/application/app.js' %}
    
    <link rel="icon" href="{% static "favicon.ico" %}">
    <title>GEN.cv | home</title>
</head>


    {% block title %}<title>GEN.cv | home</title>{% endblock %}
    <body class='flex flex-col justify-center items-center min-h-screen m-0 p-0 max-w-[1024px] mx-auto'>
    {% block navigation %}
    <nav class="bg-primary p-4 text-white w-full">
        <div class='container mx-auto flex justify-between'>
            <a class='text-2xl' href="{% url 'pages:home' %}">GEN.cv</a>
            <div class='flex space-x-4 text-lg'>
                {% if not user.is_authenticated %}
                    <a href="{% url 'users:login' %}">Se connecter</a>
                    <a class=".monbouton  mr-6 lg:mr-0" href="{% url 'users:signup' %}">S'inscrire</a>
                {% else %}
                <form method="post" action="{% url 'users:logout' %}">
                    {% csrf_token %}
                    <button class='hover:text-red-500 transition duration-500 mr-6 lg:mr-0' type='submit'>Se déconnecter</button>
                </form>
                {% endif %}
            </div>
        </div>
    </nav>
    {% endblock navigation %}

    <div class="flex-grow">
        {% block content %}{% endblock content %}
    </div>

    {% block footer %}
        <footer class="bg-primary p-4 text-white w-full h-auto mt-6 flex flex-row justify-center items-center">
            <div class='container mx-auto flex justify-start items-center'>
                <p>© 2021 GEN.cv</p>
            </div>
        </footer>
    {% endblock footer %}
</body>
<html>